### ISSUE TITLE
Cannot compile samples

### ISSUE THREAD

**Issue by dashpritam** [andreacasalino/Easy-Factor-Graph#32]
Hi, 
The build was successful, but when I compile the samples I get the following error.

 `g++ Sample01-2-Factors.cpp 
Sample01-2-Factors.cpp:9:10: fatal error: EasyFactorGraph/categoric/GroupRange.h: No such file or directory
    9 | #include <EasyFactorGraph/categoric/GroupRange.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`
I did set LIB_OPT ON (Line 3 in CMakeList.txt)

Any suggestions? I'm using G++ 10 on ubuntu 18.

**Comment by dashpritam** [comment]
Something does not add up in your CMake files. After building the project, in /usr/local/include/ I see a library EFG (/usr/local/include/EFG). But your examples show #include<EasyFactorGraph/categoric/...> this is why the compiler cannot find the headers. 

I also tried renaming the include directory to /usr/local/include/EasyFactorGraph/ instead of /usr/local/include/EFG/EasyFactorGraph/. But this results in namespace error which also seems like some path issues.

**Comment by andreacasalino** [comment]
Dear Pritam,

first of all thank you for your interest in this library.

The include in the samples are done in that way because the 'src/header' folder location is made public by the cmake instruction 'target_include_directories' (line 15 of 'cmake/MakeLibrary.cmake').
To enable this feature you actually need to set up your project with CMake and then use make or ninja inside the generated folder.
Alternatively, you can also use an IDE like VS code with the cmake extension, that does this automatically for you.
DO NOT compile with gcc by hand.

Could you please tell exactly the steps that you follow to compile the project?

The LIB_OPT option allows you to compile EFG as a shared library and has nothing to do with this issue.
